version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=threatdb
      - COLLECTION_NAME=threats
      - CSV_PATH=/app/data/cyber_threats.csv
    volumes:
      - ./data:/app/data 
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
